<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDGxwPgr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDGxwPgr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDGxwPgr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDGxwPgr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDGxwPgr\App_KernelDevDebugContainer([
    'container.build_hash' => 'DGxwPgr',
    'container.build_id' => 'd35b7453',
    'container.build_time' => 1648993409,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDGxwPgr');
